server:
  port: 8080
spring:
  application:
    name: course
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:cccat16-test;INIT=RUNSCRIPT FROM 'classpath:h2/schema.sql';DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: