server:
  port: 8081
spring:
  application:
    name: payment
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:cccat16;INIT=RUNSCRIPT FROM 'classpath:h2/schema.sql';DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue: rideCompleted
    exchange: rideCompleted